### ISSUE TITLE
inquiry about the global image feature of the given image from windowvisiontransformer 

### ISSUE THREAD

**Issue by pipiofzl** [caoyunkang/WinClip#2]
dear authors, 
     While reproducing your repo, I had a problem acquiring the tensor of full scale image feature of the given image from sliding window mechanism.
Currently, I am looking at the `class WindowVisionTransformer(nn.Module)` in **transformer.py** since there is a caption, # L: 0:N1, small scales (2x2), N1:N2, mid scales (3x3), N2:L: large scale (full), at line 705 of **transformer.py** file, am I looking at the correct file? If not, where can I find the results I am looking for?

Thanks for your help in advance and look forward to your reply.

Best

**Comment by caoyunkang** [comment]
Thanks for your interest. You have referred to the correct line. Please further refer to line 708-755 for detailed implementations. Best.
